### ISSUE TITLE
It will be very comfortable, if accounts of web and mobile version can synchronize.

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#14]
**Describe the solution you'd like**
It is needed to create a separate account for web version of program. And you can fill in different information to the program in web and mobile version, as you have two account.
It would be really great, if all information in web and mobile version will sync and you can open, edit or delete it in different devises the same tasks.

**Comment by vpeycheva** [comment]
They are synchronized. If you have problems, try login in with your account on the beta web app. Here is a link: https://app.tobidun.io/
The alpha web application is: https://app.tododone.io/

**Comment by Viktoriia-Chumak** [comment]
I log in to my account on the beta web app, alpha web app and alpha mobile app.
On mobile app there are new view of the program (as in alpha web app), but old tasks (as in beta web app). 
![alpha mobile app](https://user-images.githubusercontent.com/65408344/82352455-02f1ca80-99cc-11ea-8c5e-eb490657f355.jpg)
![alpha mobile app2](https://user-images.githubusercontent.com/65408344/82352459-04bb8e00-99cc-11ea-9a3b-62ee0ba5af34.jpg)
![alpha web app](https://user-images.githubusercontent.com/65408344/82352462-05ecbb00-99cc-11ea-8fd7-669972a0b614.jpg)
![beta web app](https://user-images.githubusercontent.com/65408344/82352466-06855180-99cc-11ea-8e7f-c9bdf6b60933.jpg)

**Comment by duy-a** [comment]
I agree that it was very confusing to test the web and android versions when the tasks and accounts are not synchronized.

Have released an update that the account & data will be the same across the devices. Meaning, **open beta** (https://app.tobidun.io); **alpha** (https://app.tododone.io) &&  **android** will have the same data. The difference now will be:

- Open beta: will use the latest ready production (i.e - **no** "Next 7 days" section)
- Alpha: with newest features and bugs (if any)
- Android = alpha (unless you have installed a public version, which means android = open beta)

_android public version = if you installed via a google play store by searching for an app, instead of using a sign up link_

- Public version: https://play.google.com/store/apps/details?id=io.tobidun.app
- Alpha version (sign-up link): https://play.google.com/apps/testing/io.tobidun.app

So from this moment forward, please use your android account to login.

I hope this clarifies and helps with the situation and testing.

Cheers & have a great day/ evening :)

**Comment by Viktoriia-Chumak** [comment]
Thank you. Now all data in beta, alpha and android (I have alpha version) is the same. 
Have a good day/evening!
