### ISSUE TITLE
Manual input for reminder time not possible

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#26]
**Description**
The manual input of time for reminder is not possible. When I try to delete the automatic input, the keyboarded collapses. 

**To Reproduce**
1. Open web app
2. Create new task or edit an existing one
3. Click on Remind At
4. Choose a date
5. Click on time box and try to delete old data

**Expected behavior**
Data is deleted and you can input new one.

**Actual behavior**
Deleting is not possible, input can be done only if automatic hour is 0-9 AM

**Screenshots**
![20200630-181057](https://user-images.githubusercontent.com/65238833/86144457-5cd2cd80-bafe-11ea-8dfe-c898b3554cb3.gif)

**Desktop:**
No

**Smartphone:**
 - Nokia 6.1
 - OS Android 10

**Additional context**
There is a workaround - you can go to 0 AM using the arrows and then input  data. It will work harder for the minutes.

**Comment by duy-a** [comment]
There are 2 rules to how you can set the time

1. The time must be from 00:00 to 23:59
2. The time cannot be in the past
- i.e. if today is 01.07.2020 19:20 and the selected date is 01.07.2020 -> then the time can only be set as 19:20 the lowest. If you were able to set a 19:19, then it wouldn't make sense since it will be in the past

Will make improve to make it clearer.

**Comment by vpeycheva** [comment]
Yes, sorry my bad, I tried with the current date. Might be easier for the user is the input does not follow that type of rules, but if it is in the past or invalid, a pop up message is displayed.  Do I close this issue and open a feature request or do you prefer if I just leave it with the comment?

**Comment by duy-a** [comment]
Keeping this issue open.

**Comment by duy-a** [comment]
fix has been released to web & android alpha

**Comment by vpeycheva** [comment]
Works as expected.
